var cn = {
  dict: {
    contactUs: '聯繫我們',
    publicMetrics: '公共指標',
    ticker: '代碼',
    poolId: '權益池 ID',
    ends: '結束於',
    endsDay: ' 天',
    endsHour: ' 小時',
    endsMinute: ' 分鐘',
    currencySymbol: '¥',
    pricePair: 'ADA-CNY',
    awards: '獎項',
    howToBuy: '如何購買',
    howToStake: '如何質押',
    howToStakeTip:
      '用於質押的 ADA 永遠不會離開委託人的錢包，委託人以類似於儲蓄賬戶利息的方式獲得獎勵。委託人可以在質押後自由移動他們的 ADA，甚至可以選擇完全取消質押。',
    news: 'Cardano 新聞',
    signUp: '註冊',
    subscribe: '註冊以接收更新消息',
    phone: '電話',
    name: '姓名',
    firstName: '名',
    lastName: '姓',
    email: '電子郵件',
    emailAddress: '電子郵件地址',
    emailSubject: '標題',
    emailBody: '內容',
    countryCodeDescription: '電話號碼包括國家代碼',
    supporter: 'ADApools.org 最高等級支持者',
    poolDescription:
      '我們的權益池是新的，需要您的幫助才能更大的發展。我們承諾永遠不會錯過任何一個區塊。通過零利潤、多層安全性、24/7 全天候監控、高性能節點和地理冗餘連接來最大化您的回報。',
    coinQuora: 'https://coinquora.com/zh-hans/?s=cardano',
    cointelegraph: 'https://cointelegraphcn.com/search?query=Cardano',
    epoch: '時代 ',
    epochTip: 'Cardano 平臺將時間分成稱為時代的時期。一個時代大約持續 5 天。',
    price: '價格',
    priceTip: 'Cardano 中國人民幣價格',
    relays: '傳達節點',
    relaysTip:
      '傳達節點充當核心網絡節點和互聯網之間的代理，圍繞著核心節點建立安全邊界。傳達節點確保核心節點和區塊鏈的完整性的完整，即使一個或多個傳達節點受到損害。',
    pledge: '池主應諾質押量',
    pledgeTip: '權益池池主應諾的質押量。',
    totalStake: '池現有質押量',
    totalStakeTip: '實時所有委託人總質押量。',
    delegators: '委託人數',
    delegatorsTip: '委託給權益池的錢包數量。',
    margin: '可變費用',
    marginTip: '在固定費用後，權益池主獲得的總獎勵的百分比。',
    fixedCost: '固定費用',
    fixedCostTip:
      '池的固定費用取自於每個時代的獎勵。該費用由池的所有委託人共享，而不是每個委託人。最小值為 340 ADA。',
    lifetimeROA: '總平均收益率',
    lifetimeROATip:
      'ADA 的估計回報，根據終身質押獎勵按年計算。池主獎勵不包括在計算中。',
    epochBlocks: '時代區塊量',
    epochBlocksTip: '這時代鑄造區塊的數量。',
    lifetimeBlocks: '总區塊量',
    lifetimeBlocksTip: '终身鑄造區塊的數量。',
    lifetimeLuck: '權益池总运气',
    lifetimeLuckTip:
      '衡量已產生的區塊數量與權益池預期產生的數量。從長遠來看，運氣平均為 100%。',
    buyOn: '可購買的平臺: ',
    stakeOn: '可質押的平臺: ',
    submit: '提交',
    contactUsDescription:
      '如果您有任何問題或意見，請通過電子郵件或電話與我們聯繫，或使用聯繫表給我們發送消息。',
  },
};
